steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/${_GITPROJ}/${_GITREPO}.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJID}/${_GCRREPO}:${_VERSION}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJID}/${_GCRREPO}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJID}/${_GCRREPO}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
  _GITPROJ: bershin
  _GITREPO: bj-cloud-build
  _PROJID: bj-config-connect
  _GCRREPO: simple-server
  _VERSION: v2.0

  _DEPLOYMENTNAME: simple-server-deployment
  _CONTAINERNAME: simple-server
  _ZONE: europe-west4-a
  _GKE_CLUSTER: cb-cluster

  
options:
  substitution_option: 'ALLOW_LOOSE'